from __future__ import annotations

from collections.abc import Iterable


def command_id(parts: tuple[str, ...] | Iterable[str] | str) -> str:
    if isinstance(parts, str):
        return parts
    return ".".join(parts)


LOGGED_COMMANDS = {
    "init",
    "source.add",
    "source.rehash",
    "source.scan",
    "source.verify",
    "source.delta",
    "source.coverage",
    "source.lint",
    "file.write",
    "file.append",
    "file.prepend",
    "file.move",
    "file.rename",
    "file.delete",
    "daily.append",
    "daily.prepend",
    "property.set",
    "property.remove",
    "property.aliases",
    "task.toggle",
    "task.set",
    "vault.init",
    "vault.register",
    "vault.doctor",
    "vault.build",
    "vault.lint",
    "vault.maintain",
    "status",
    "query",
    "page.create",
    "page.update",
    "page.move",
    "page.delete",
    "catalog.build",
    "catalog.rebuild",
    "index.build",
    "note.new",
    "note.normalize",
    "links.check",
    "links.normalize",
    "links.unresolved",
    "links.orphans",
    "links.deadends",
    "ingest",
    "ingest.status",
    "ingest.plan",
    "ingest.finish",
    "lint",
    "doctor",
    "audit",
    "agents.compile",
    "review.resolve",
    "review.add",
}


CHANGE_POLICY_COMMANDS = {
    "init",
    "source.add",
    "source.rehash",
    "source.scan",
    "file.write",
    "file.append",
    "file.prepend",
    "file.move",
    "file.rename",
    "file.delete",
    "daily.append",
    "daily.prepend",
    "property.set",
    "property.remove",
    "property.aliases",
    "task.toggle",
    "task.set",
    "vault.init",
    "vault.register",
    "vault.build",
    "vault.maintain",
    "page.create",
    "page.update",
    "page.move",
    "page.delete",
    "catalog.build",
    "catalog.rebuild",
    "index.build",
    "note.new",
    "note.normalize",
    "links.normalize",
    "ingest.finish",
    "agents.compile",
    "review.resolve",
    "review.add",
}


AUDIT_POLICY_COMMANDS = {
    "ingest",
    "status",
    "query",
    "lint",
    "vault.lint",
    "doctor",
    "vault.doctor",
    "audit",
    "links.check",
    "links.unresolved",
    "links.orphans",
    "links.deadends",
    "source.verify",
    "source.delta",
    "source.coverage",
    "source.lint",
    "ingest.status",
    "ingest.plan",
}
