[codecrate]
output = "context_wikimason.md"
keep_docstrings = true
dedupe = true
respect_gitignore = true
# exclude = ["*/.venv/*", "integration_tests", "examples", "docs"]
gitignore_allow = ["wikimason/_version.py"]
exclude = ["*/.venv/*", "integration_tests", "todo.md"]
include = ["**/*.py", "**/*.toml", "**/*.rst", "**/*.md", "**/*.typed", "**/*.js", "**/*.css", "**/*.html", "**/*.ts", "**/*.json"]
split_max_chars = 0
manifest = false
layout = "full"
profile = "portable-agent"
emit_standalone_unpacker = true
